require: rubocop-rails

Style/Documentation:
  Enabled: false
Lint/EnsureReturn:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false